### ISSUE TITLE
OpenCV issue?

### ISSUE THREAD

**Issue by arianaray** [PyLorentz/PyLorentz#35]
Hi, I ran into a compatibility issue with OpenCV. (Windows 10 computer). 

I followed the instructions for using the .yml file to create the PyLorentz environment, but when I open an example Jupyter notebook I get an error saying "no module cv2 found". If I then try to install opencv or opencv3 I get conflict issues and it doesn't work. I went around this by creating a new environment and installing opencv first and letting it choose the python version and dependencies that worked best for it, then manually installing hyperspy, which took care of the other PyLorentz dependencies. But, then the version of scikit image was 0.19 and not 0.15 as specified in the .yml file, so the module "skimage.external.tifffile" has been replaced with "skimage.io.imsave". I resolved this by modifying or commenting out all instances of "tifffile" in the source code and it works fine now. 

If there was a better way of doing this, please let me know. Otherwise, hope this is helpful for future people :) Thanks for the code!

**Comment by Art-MC** [comment]
Awesome, thanks for letting us know! I'd like to remove the OpenCV dependency altogether, so this is good motivation for doing that and making things compatible with the newest version of scikit-image.

**Comment by Art-MC** [comment]
The new environment no longer requires opencv, and the scikit-image bug has been removed as well. Thanks for letting us know!
