### ISSUE TITLE
qt4 load issue

### ISSUE THREAD

**Issue by JeanLeu** [PyLorentz/PyLorentz#46]
Hi, I met a problem when run the code. The environment was installed successfully. When I ran the PyLorentz_GUI.py, an Error appeared. 
" File "C:\Users\jian.liu2\AppData\Local\miniconda3\envs\pylorentz\lib\site-packages\pyface\base_toolkit.py", line 246, in import_toolkit
    raise RuntimeError(msg)
RuntimeError: No traitsui.toolkits plugin could be loaded for qt4".

The code was run on a Win10 computer, and the bUnwarpJ_2_images.bsh file was copied to FIJI Plugin folder. Do you have any idea on how to solve this problem, please? Many thanks.

**Comment by trcote** [comment]
Hi, accidentally closed this before we're sure it's fixed. Just as a quick note, image registration is no longer a feature of PyLorentz. However you can still use the bUnwarpJ script as a smaller plugin within FIJI.

As far as the runtime error, try using the newest commit of PyLorentz. I think you might be using an old version that has some dependencies that might not work. If this issue still persists after that, let me know. Its odd as PyLorentz does not run on qt4.

**Comment by JeanLeu** [comment]
Hi, thank you very much, I downloaded the latest version, and the code runs well. I used anaconda to make an environment and the pyqt version is 5.15.7. Thanks again for your help.
