### ISSUE TITLE
Output image failed

### ISSUE THREAD

**Issue by Donghai001** [PyLorentz/PyLorentz#62]
Dear developer,

Thank you for designing this excellent software package. It's really nice to use this software package into my work. But here I found some problems in latest version Pylorentz V2.0

(1) In the Jupyter notebook '02_SIM_demo.ipynb', the method `tfs.show_tfs()` located below the section 'Imaging conditions' did not execute as expected; it failed to display an image without any warnings or errors. I encountered this issue after transferring the code to PyCharm IDE and substituting the OVF file with my own. In contrast, the methods `simulator.visualize(xy_only=True)` and `simulator.show_phase()` functioned correctly, successfully producing the desired images.
The code exhibiting the issue is presented below.
```python
tfs = simulator.sim_TFS(
    defocus_values=defvals,
    scope=scope,
    amorphous_bkg=300,
    flip = False,
)
tfs.show_tfs()
```

(2) If I defined a series of defocus in a list, for example, `defvals = [6e3,4e3]`, what I expected is that it can produce 2 images. However, it just output one image with defoucs=6e3 with the console output message `Simulating images for defocus values: 6 um, 4 um`. And there was not any warmings or errors.
The code exhibiting the issue is presented below.
```python
defvals = [6e3,4e3]
dd = simulator.sim_images(defocus_values=defvals,
    scope=scope,
    amorphous_bkg=300,
    flip = False,)
dd.show_im()
```
My python interpreter version is 3.12. Please let me know if you need other information to diagnose this issue, I am looking forward to your reply :)

Best,
Donghai

**Comment by Art-MC** [comment]
Hi Donghai, 

Thanks for letting me know! I am having a hard time reproducing your first issue, and I'll admit I'm a little unsure as to why show_tfs() would fail but other .visualize() would work. Does running `show_im(tfs.imstack[0])` work? And if so, can you try the following lines: 
```python
fig, ax = plt.subplots()
show_im(tfs.imstack[0], figax=(fig, ax))
plt.show()
```
^that code is basically all that show_tfs() is doing, so it's strange that it would fail there. It's possibly a pyCharm thing, but I can't easily test that unfortunately. 

As for the show_im() only showing one image, that is how it was intended but I understand how it's confusing. I updated it to be more clear that it's only showing one image of X, and I also added the new `dd.show_all()` method which should do what you wanted. 

I just pulled everything into main, so let me know if you have any further questions or if I created more bugs :)

**Comment by Donghai001** [comment]
Dear Arthur,

Thank you for your helpful response. Indeed, the code you provided operates correctly. However, I still encounter issues with the `tfs.show_tfs()` function in the latest main branch, which might be related to my PyCharm environment. Nonetheless, substituting `tfs.show_tfs()` with the code you offered is an acceptable solution :)

I have a further question regarding the output image resolution. I've noticed that the resolution of the generated images is somewhat low, particularly around the core of the skyrmion, as can be seen in the attached example where the central square is visible. Are there any suggestions for enhancing the resolution of these images?

I'm grateful for the help you've provided and looking forward to your reply :)

Best,
Donghai

---------
Following is the attached image
![simulation_skyrmion_phase](https://github.com/user-attachments/assets/18a91466-51f5-4f2a-b527-6e13266e8874)

**Comment by Donghai001** [comment]
Dear Arthur,

Thank you for responding to my question. Yes, the attached magnetic pattern is from the artifact set by inserting a skyrmion in MuMax. I appreciate your suggestion to do a light Gaussian blur for a simple test. 

I would like to extend my thanks to you once more for your invaluable help.

Best,
Donghai
