### ISSUE TITLE
Read Binary8 file failed

### ISSUE THREAD

**Issue by Donghai001** [PyLorentz/PyLorentz#66]
Dear developers,

I have encountered an issue with Pylorentz while attempting to read Binary 8 OVF files.
In the file ` Pyloretz/io/ovf.py ` specifically lines 135 through 139, the code reads as follows:
```python
     elif dtype == "bin8":
        data = np.fromfile(
            file, dtype="f", count=xsize * ysize * zsize * 3, offset=header_length + 8
        )
    else:
```
In my testing, I've found that the data type should be changed from  `dtype = 'f'`  to  `dtype= 'd' `.

Here I have a skyrmion contained within a binary 8 OVF file for your reference :）https://drive.google.com/file/d/10j6voV9sANCpGHx6dIYQhFmNf0flswWY/view?usp=sharing

Best,
Donghai

**Comment by Art-MC** [comment]
Thanks for letting us know :) I will get to this in a few days as it seems like you've already found a fix.

**Comment by Donghai001** [comment]
Actually, I saw the OOMMF official website(https://math.nist.gov/oommf/doc/userguide20b0/userguidexml/sec_ovf20format.html) that introduce the OVF format. It mentioned that binary 8  is 8-byte format and `double` has 8 bytes. So, it could not use `float` (4 bytes)to read the binary 8. In my desktop it works fine with small thickness OVF file(for example, the file I attached above link) if I change `dtype = 'f'`to `dtype= 'd'`. 

However, after changing `dtype='f'` to `dtype='d'` in Pylorentz, I encountered an error for OVF files with large thicknesses: `UserWarning: Amplitude is uniform and has a low value: 0.0. Consider increasing sample xip0 or decreasing sample thickness`. Interestingly, this error does not occur when the same OVF file is converted to bin4 or text format.

**Comment by Art-MC** [comment]
Thanks! The user warning is just letting you know that for the given material parameters, it's likely that you should be using a larger extinction distance (xip0), as you're not getting enough electrons through your sample. Honestly it's a parameter that isn't normally too useful, and the 50 nm value given as an example in the notebook is maybe too low. 

I fixed the read_ovf function as per your suggestion and will pull into main shortly. Thanks again :)

**Comment by Donghai001** [comment]
Dear Arthur,

Thanks for you consider this issue. Now I look at the `main` branch and `dev` branch. But why you change the bin 4 `dtype='f'` to `dtype='d' ` :) ? I apologize if my previous explanation was unclear. I intended to convey that only the `dtype` for bin8 should be changed from `f` to `d`. The line130 to line 138 **should** be:

```python
    elif dtype == "bin4":
        # for binaries it has to give count or else will take comments at end as well
        data = np.fromfile(
            file, dtype="f", count=xsize * ysize * zsize * 3, offset=header_length + 4
        )
    elif dtype == "bin8":
        data = np.fromfile(
            file, dtype="d", count=xsize * ysize * zsize * 3, offset=header_length + 8
        )
```
In line `elif dtype == "bin4"` it should be `dtype="f"`, but in line `elif  dtype == "bin8" ` it should be `dtype="d"`. Please check this again. I truly appreciate the attention you've given to this matter.  :)

Best, 
Donghai

**Comment by Art-MC** [comment]
ah my bad-- will do a quick fix on that
