### ISSUE TITLE
defocus= 0 still has image

### ISSUE THREAD

**Issue by Donghi007** [PyLorentz/PyLorentz#75]
Hi~ I encounter a problem regarding defocus =0 nm. 
In my local, I have an OVF file that shows two shyrmions. If I set the defocus=0, it still shows the skyrmion. However, in the Pylorentz 1.0, did not has this problem.

Looking forward to your reply :)

Here I attached two images for your reference, the first one is generate by latest version for defocus=0, the second is by V1.0:
![image](https://github.com/user-attachments/assets/9cfbb495-a543-4cb2-b3bd-c74404f1b7ee)
![image](https://github.com/user-attachments/assets/7ea2435d-dbb7-4913-b4ae-9d2ec2bc07b4)

**Comment by arthurmccray** [comment]
Hm, that is odd. If you display the single image (that shows contrast now with zero defocus) with a colorbar, what is the scale? You can do this with ``show_im(dd.images[i])`` using the naming convention from the sim_demo notebook, or just pass ``cbar=True`` to whatever `.visualize()` function you are using. 

I suspect that the contrast range is very very small, and therefore what you're seeing is effectively an artifact. When showing multiple images (such as in a tfs) there is some contrast normalization across the images that hides this kind of thing, and in the past as well it existed for single images. This is something i've been playing around with thoughand I might have to change it back if that is the case. 

If it seems like the display is correct then maybe you can send me the phase image or ovf and I can mess around with it? Hopefully it's just a contrast thing though.

**Comment by Donghi007** [comment]
Hi, you are right, the contrast range is very very small by showing `cbar=True` in the notebook. I attached the picture and OVF file in the end.  But I hope to know is there any method can cancel this artifact simply? As you mentioned above, I will try normalization the images when defocus =0 later. Thanks for your help :)


![image](https://github.com/user-attachments/assets/e96e7612-6678-4dfb-b7e6-1f466590741d)
OVF : https://drive.google.com/file/d/15-VUrFdRwH9ujHgtGsi_0L79tmzE-iQm/view?usp=sharing

**Comment by arthurmccray** [comment]
There unfortunately isn't a way to do so without potentially introducing other unintended consequences later, where a user might have contrast hidden that they were expecting to see. The best solution is for the user to set the vmin and vmax values themselves (passed as arguments into the `show` or `visualize` call) to a reasonable value for their particular circumstances. This would likely be set by the max/min values of an image with a normal defocus, and this is what is used as an example in the sim_demo notebook. 

As currently written, if the peak-to-peak range of the image is less than 1e-12 and `cbar=False`, then the vmin and vmax are set to 1e-12 above or below the peak values; this is intended to prevent users from seeing an artifact and thinking it was real contrast (as happened here, evidently the contrast range was > 1e-12). I could increase this value, but I don't think there's a perfect cutoff that would work for any situation, and I'd rather err on the side of showing artifacts than not showing signal. 

I hope this helps!

![image](https://github.com/user-attachments/assets/c3d5a223-0541-4b8d-939c-3b50aa2033cb)
![image](https://github.com/user-attachments/assets/ee2edbc2-f499-4c3b-8c02-6b52bc09af53)

**Comment by Donghi007** [comment]
Thank you very much for your help. Now it  works fine if I set vmin and vmax for defocus=0! :)
